#!/usr/bin/bash
set -e

help() {
	echo "Commands: install, uninstall"
}


if [ ! -n "$1" ]; then
	echo "Missing argument"
	help
	exit 1
fi

if [ $1 == "install" ]; then

	sudo mkdir -p "/etc/lockd/"{profiles,stores}

	sudo rm "/usr/bin/lockd" 2>/dev/null
	sudo cp "out/lockd" "/usr/bin/lockd"
	sudo chown root:root "/usr/bin/lockd"
	sudo chmod 4755 "/usr/bin/lockd"

	sudo chmod 0755 "/etc/lockd"
	sudo chmod 0755 "/etc/lockd/profiles"
	sudo chmod 0700 "/etc/lockd/stores"

elif [ $1 == "uninstall" ]; then
	sudo rm "/usr/bin/lockd"
	sudo rm -r "/etc/lockd"
else
	help
	exit 1
fi
