#!/usr/bin/bash
set -e

NAME="$1"
STORE="$2"
MOUNT="$3"
RUN="$4"

# echo "$NAME"
# echo "$STORE"
# echo "$MOUNT"
# echo "$RUN"

# TODO: verify these variables are set
# Other than mkdir, this shouldn't cause issues at least

mkdir -p "$MOUNT"
chown "$NAME":"$NAME" "$MOUNT"

mount "$STORE" "$MOUNT" && \
  chown "$NAME":"$NAME" "$MOUNT" && \
  sudo -u "$NAME" "$RUN"

umount "$MOUNT"
